In [4]:
import numpy as np

In [11]:
data1=[0,1,2,3,4,5]
a1=np.array(data1)
print(a1)

[0 1 2 3 4 5]


In [12]:
print(type(a1))

<class 'numpy.ndarray'>


In [13]:
data1=[0,1,2,3,4.5,5]
a2=np.array(data1)
print(a2)

[0.  1.  2.  3.  4.5 5. ]


In [14]:
print(a1.dtype)
print(a2.dtype)

int32
float64


In [15]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
l=[[1,2,3],[4,5,6],[7,8,9]]
print(l)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [17]:
a=np.arange(5)
print(a)

[0 1 2 3 4]


In [20]:
a=np.arange(0,10,2)
print(a)

[0 2 4 6 8]


In [21]:
a=np.arange(12).reshape(4,3)
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [33]:
a=np.arange(27).reshape(3,3,-1)
print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [35]:
a=np.arange(12).reshape(-1,3)
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [36]:
print(a.shape)

(4, 3)


In [37]:
a=np.linspace(1,10,10)
print(a)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [38]:
a=np.linspace(1,10,8)
print(a)

[ 1.          2.28571429  3.57142857  4.85714286  6.14285714  7.42857143
  8.71428571 10.        ]


In [39]:
a=np.linspace(0,np.pi,20)
print(a)

[0.         0.16534698 0.33069396 0.49604095 0.66138793 0.82673491
 0.99208189 1.15742887 1.32277585 1.48812284 1.65346982 1.8188168
 1.98416378 2.14951076 2.31485774 2.48020473 2.64555171 2.81089869
 2.97624567 3.14159265]


In [41]:
a=np.zeros((3,4),int)
print(a)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [44]:
a=np.ones(5)
print(a)

[1. 1. 1. 1. 1.]


In [45]:
a=np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [46]:
a=np.array(['abc','whoami','chemistry'])
print(a)

['abc' 'whoami' 'chemistry']


In [49]:
print(a.dtype)
s='s5'
print(s.dtype)

<U9


AttributeError: 'str' object has no attribute 'dtype'

In [50]:
a=np.array(['1.567','0.123','5.2223'])
print(a.dtype
     )

<U6


In [51]:
num=a.astype(float)
print(num.dtype)

float64


In [52]:
print(num)

[1.567  0.123  5.2223]
