In [4]:
import numpy as np

In [11]:
data1=[0,1,2,3,4,5]
a1=np.array(data1)
print(a1)

[0 1 2 3 4 5]


In [12]:
print(type(a1))

<class 'numpy.ndarray'>


In [13]:
data1=[0,1,2,3,4.5,5]
a2=np.array(data1)
print(a2)

[0.  1.  2.  3.  4.5 5. ]


In [14]:
print(a1.dtype)
print(a2.dtype)

int32
float64


In [15]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
l=[[1,2,3],[4,5,6],[7,8,9]]
print(l)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [17]:
a=np.arange(5)
print(a)

[0 1 2 3 4]


In [20]:
a=np.arange(0,10,2)
print(a)

[0 2 4 6 8]


In [21]:
a=np.arange(12).reshape(4,3)
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [33]:
a=np.arange(27).reshape(3,3,-1)
print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [35]:
a=np.arange(12).reshape(-1,3)
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [36]:
print(a.shape)

(4, 3)


In [37]:
a=np.linspace(1,10,10)
print(a)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [38]:
a=np.linspace(1,10,8)
print(a)

[ 1.          2.28571429  3.57142857  4.85714286  6.14285714  7.42857143
  8.71428571 10.        ]


In [39]:
a=np.linspace(0,np.pi,20)
print(a)

[0.         0.16534698 0.33069396 0.49604095 0.66138793 0.82673491
 0.99208189 1.15742887 1.32277585 1.48812284 1.65346982 1.8188168
 1.98416378 2.14951076 2.31485774 2.48020473 2.64555171 2.81089869
 2.97624567 3.14159265]


In [41]:
a=np.zeros((3,4),int)
print(a)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [44]:
a=np.ones(5)
print(a)

[1. 1. 1. 1. 1.]


In [45]:
a=np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [46]:
a=np.array(['abc','whoami','chemistry'])
print(a)

['abc' 'whoami' 'chemistry']


In [49]:
print(a.dtype)
s='s5'
print(s.dtype)

<U9


AttributeError: 'str' object has no attribute 'dtype'

In [50]:
a=np.array(['1.567','0.123','5.2223'])
print(a.dtype
     )

<U6


In [51]:
num=a.astype(float)
print(num.dtype)

float64


In [52]:
print(num)

[1.567  0.123  5.2223]


In [2]:
import numpy as np

In [3]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
print(a[1:3,1:3])

[[5 6]
 [8 9]]


In [2]:
import sys
print(sys.path)


['C:\\Users\\ryh26\\source\\python\\python-Day1', 'C:\\Users\\ryh26\\anaconda3\\python39.zip', 'C:\\Users\\ryh26\\anaconda3\\DLLs', 'C:\\Users\\ryh26\\anaconda3\\lib', 'C:\\Users\\ryh26\\anaconda3', '', 'C:\\Users\\ryh26\\anaconda3\\lib\\site-packages', 'C:\\Users\\ryh26\\anaconda3\\lib\\site-packages\\locket-0.2.1-py3.9.egg', 'C:\\Users\\ryh26\\anaconda3\\lib\\site-packages\\win32', 'C:\\Users\\ryh26\\anaconda3\\lib\\site-packages\\win32\\lib', 'C:\\Users\\ryh26\\anaconda3\\lib\\site-packages\\Pythonwin', 'C:\\Users\\ryh26\\anaconda3\\lib\\site-packages\\IPython\\extensions', 'C:\\Users\\ryh26\\.ipython']


In [3]:
sys.path.append("C:\\Users\\ryh26\\source\\python\\python-Day1\\my_package")

In [4]:
print(sys.path)

['C:\\Users\\ryh26\\source\\python\\python-Day1', 'C:\\Users\\ryh26\\anaconda3\\python39.zip', 'C:\\Users\\ryh26\\anaconda3\\DLLs', 'C:\\Users\\ryh26\\anaconda3\\lib', 'C:\\Users\\ryh26\\anaconda3', '', 'C:\\Users\\ryh26\\anaconda3\\lib\\site-packages', 'C:\\Users\\ryh26\\anaconda3\\lib\\site-packages\\locket-0.2.1-py3.9.egg', 'C:\\Users\\ryh26\\anaconda3\\lib\\site-packages\\win32', 'C:\\Users\\ryh26\\anaconda3\\lib\\site-packages\\win32\\lib', 'C:\\Users\\ryh26\\anaconda3\\lib\\site-packages\\Pythonwin', 'C:\\Users\\ryh26\\anaconda3\\lib\\site-packages\\IPython\\extensions', 'C:\\Users\\ryh26\\.ipython', 'C:\\Users\\ryh26\\source\\python\\python-Day1\\my_package']


In [5]:
from roboadvisor.crawling import scrap as s1
s1.scrap_test()
s1.connection_test()
s1.static_test()

scrap
connection
static


In [6]:
import numpy as np

In [13]:
np.random.seed(0)

In [15]:
np.random.rand(10)

array([0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606,
       0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215])

In [16]:
x=np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [20]:
np.random.shuffle(x)
print(x)

[8 4 6 1 5 9 0 2 3 7]


In [45]:
print(np.random.choice(3,3,replace=False,p=[0.1,0.1,0.1,0.6,0.1]))

ValueError: 'a' and 'p' must have same size

In [49]:
np.random.randint(10,21,size=(3,5,3))

array([[[16, 13, 16],
        [15, 17, 10],
        [18, 14, 20],
        [16, 15, 18],
        [12, 13, 19]],

       [[17, 15, 13],
        [14, 15, 13],
        [13, 17, 19],
        [19, 19, 17],
        [13, 20, 12]],

       [[13, 19, 20],
        [17, 17, 15],
        [11, 12, 12],
        [18, 11, 15],
        [18, 14, 10]]])

In [64]:
a1=np.random.randint(0,7,size=100000)

print(a1.mean())


3.00763


In [ ]:
import numpy as np

In [2]:
a2=5.0
int sum=0
    while np.random.randn()
        sum++
        print(1)
        if np.random.randn()==1
            break;
print(sum)

SyntaxError: invalid syntax (Temp/ipykernel_11700/3675130081.py, line 2)

In [13]:
import numpy as np

In [25]:
a=np.random.randint(10,20,size=5)
print(a)
count=np.bincount(a,minlength(10,20)
print(count)

SyntaxError: invalid syntax (Temp/ipykernel_22276/1753589245.py, line 4)